services:
  client:
    container_name: client-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: techwire/food-delivery:1.0.0
    ports:
      - "2000:2000"
    networks:
      - mynetwork

  web:
    image: nginx:mainline-alpine-slim
    container_name: nginx_service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./nginx/private.key:/etc/ssl/private/private.key
      - ./nginx/snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/snippets/proxy-params.conf:/etc/nginx/snippets/proxy-params.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
