name: Docker Compose - Deploy to DockerHub

on:
  push:
    branches: [ "production" ]

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Login to DockerHub Registry
        #        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        run: echo HelloWorld123 | docker login -u techwire --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push
        working-directory: ./client-v2